version: '3.5'

services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../certs:/certs:ro
      - ../content:/srv/http:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
