version: '3.7'

services:
  syncthing:
    image: syncthing/syncthing
    volumes:
      - ../syncthing:/var/syncthing
    network_mode: host
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ../certs:/certs:ro
      - ../srv:/srv:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/include.d:/etc/nginx/include.d:ro
    network_mode: host
    restart: always
